# e2e_decode Makefile。SCAFFOLD。需 link FlashMLA 编好的对象/头文件。
TARGET := e2e_decode
include ../../../../../microbench/common/common.mk
# TODO(impl): e2e 需要 FlashMLA 的 kernel 实现（.cu 实例化），
#   或链接已 pip install 的 flash_mla.cuda 扩展。补 -L/-l 或把 instantiations/*.cu 一起编。
